main:
  # - name: Blog
  #   url: post
  #   weight: 10
  # - name: Publications
  #   url: publication
  #   weight: 20
  - name: People
    url: people
    weight: 30
  # - name: News
  #   url: news
  #   weight: 20
  # - name: Events
  #   url: events
  #   weight: 40
  